version: "3.8"

services:
  neo4j:
    image: neo4j
    container_name: neo4j-container
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/strongpassword123 # Contraseña válida
      - NEO4J_dbms_security_auth__minimum__password__length=4 # Reducir requisito de longitud (opcional)
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/import
      - ./neo4j/plugins:/plugins
